import './globals.css'
import type { Metadata } from 'next'
import { Questrial, Orelega_One } from 'next/font/google';

const orelega = Orelega_One({
  subsets: ["latin-ext"],
  weight: '400'
});

const questrial = Questrial({
  subsets: ["latin-ext"],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Emerald Necklace Conservancy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={orelega.className}>{children}</body>
    </html>
  )
}
