import './globals.css'
import type { Metadata } from 'next'
import { Inter, Orelega_One } from 'next/font/google';

const orlega = Orelega_One({
  subsets: ["latin-ext"],
  weight: '400'
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={orlega.className}>{children}</body>
    </html>
  )
}

// export function MapLayout({ children }) {
//     return (
//       <html lang="en">
//         <body className="bg-map">{children}</body>
//       </html>
//     )
// }
