import './globals.css'
import type { Metadata } from 'next'
import { Inter, Orelega_One } from 'next/font/google';

const orlega = Orelega_One({
  subsets: ["latin-ext"],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Emerald Necklace Conservancy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={orlega.className}>{children}</body>
    </html>
  )
}
